### ISSUE TITLE
Mission 3 - SRS: Feedback

### ISSUE THREAD

**Issue by kob-e** [benhuri/Mifalot#7]
## TODO:
- Please attach here the Client review.

## סיכום פגישתנו:
פרויקט לא הנדסי עד הסוף, דרישות לא ברורות עד הסוף, צריך לבדוק האם סיכונים ממשיים

**Comment by benhuri** [comment]
Hey,
We have added the review at the last page of the SRS.
We opened issues following the main points of the meeting with Tomer.
Tomer also said he sent you and Hadas a review about our job, so I'm not sure that we should attach it to here too (I didn't ask it from him, Because i guess it's private).
Please let us know if it's ok, and see the issues we have opened too.

Thanks.
